[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
simpan_data = "DyK22yV8aBuyYSHw9kRnrR2UYBnVDasxczsLSQ2uVpEb"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bash ./test.sh"

[hooks]
