[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
simpan_data = "74ZKdLoWz7Kee2tVJY9RGR88K2ss1vnzCsQfrFhdgkiJ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
